create role DBA;
create warehouse Generic;
grant role DBA to role accountadmin;
grant ownership on warehouse Generic to role DBA;
grant ownership on role DBA to role accountadmin;
use role DBA;
use warehouse Generic;
use role accountadmin;
grant create warehouse, create database, create role on account to role DBA;
grant manage grants, monitor usage, manage user support cases on account to role DBA;
grant create integration on account to role DBA;
use role DBA;
create role readonly;
create role readwrite;
create role fullaccess;
grant ownership on role readonly to role DBA;
grant ownership on role readwrite to role DBA;
grant ownership on role fullaccess to role DBA;
grant role readonly to role readwrite;
grant role readwrite to role fullaccess;
grant role fullaccess to role DBA;
create database DBDEMO;
create schema DBDEMO.raw;
create schema DBDEMO.int;
create schema DBDEMO.prs;